name: 'Variables: create or update repository variable'
description: Creates or updates a variable value on a repository
author: Peter Murray

inputs:
  github_token:
    description: The GitHub token that has 'repo:admin' permissions (or variables:write for fine grained permissions) to access and modify variables on the specified repository
    required: true

  repository:
    description: The full path to the repository to save the variable to
    required: true

  variable:
    description: The name of the variable to add or update
    required: true

  value:
    description: The value for the variable to be stored
    required: true

  overwrite_existing:
    description: Flag to overwrite an existing secret
    default: true
    required: false
    
runs:
  using: node20
  main: '../dist/create-or-update-repository-variable/index.js'